#
# Exception view configuration for the Fusion Parser
#

Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          fusionParserExceptions:
            matchingExceptionClassNames: ['Neos\Fusion\Core\ObjectTreeParser\Exception\ParserException']
            options:
              logException: true
              viewClassName: Neos\Fusion\View\FusionView
              viewOptions:
                fusionPath: 'Neos/Fusion/FusionParserException'
                fusionPathPatterns: ['resource://Neos.Neos/Private/Fusion/Error/Root.fusion']
                enableContentCache: false
              variables:
                flowPathRoot: '%FLOW_PATH_ROOT%'
